### ISSUE TITLE
File not found even when i gave the path correctly in the hyper_params file...

### ISSUE THREAD

**Issue by DhanushDK17** [Kyubyong/tacotron#102]
File "prepro.py", line 17, in <module>
    fpaths, _, _ = load_data() # list
  File "E:\Final year project\tacotron-master\tacotron-master\data_load.py", line 42, in load_data
    lines = codecs.open(transcript, 'r', 'utf-8').readlines()
  File "C:\pydazz_env\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '\\data\\transcript.csv'

**Comment by eboshii** [comment]
I have this same issue, how did you fix it?

**Comment by kouohhashi** [comment]
Hi I have the same issue. 
Is this because LJSpeech-1.1 don't have transcript.csv?
