### ISSUE TITLE
Getting around: raise ValueError("Can't load save_path when it is None.") ?

### ISSUE THREAD

**Issue by CoderReece** [Kyubyong/tacotron#112]
I can't get synthesize to execute.
`python synthesize.py
Graph loaded
Traceback (most recent call last):
  File "synthesize.py", line 48, in <module>
    synthesize()
  File "synthesize.py", line 32, in synthesize
    saver.restore(sess, tf.train.latest_checkpoint(hp.logdir)); print("Restored!")
  File "C:\Users\Reece\Miniconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1796, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.`

**Comment by CoderReece** [comment]
Didn't realise it had a configuration. Stupid me.

**Comment by ishandutta2007** [comment]
Yeah but in configuration what should be changed to what ?
I have already created `logdir/01`

**Comment by ishandutta2007** [comment]
you have to copy the following to `logdir/01`
```
checkpoint                     
graph.pbtxt                       
model_gs_200k.data-00000-of-00001  
model_gs_200k.index                
model_gs_200k.meta
```

**Comment by rookiefront** [comment]
> 您必须将以下内容复制到 `logdir/01`
> 
> ```
> checkpoint                     
> graph.pbtxt                       
> model_gs_200k.data-00000-of-00001  
> model_gs_200k.index                
> model_gs_200k.meta
> ```
model_gs_200k Where does the weight come from
![image](https://user-images.githubusercontent.com/28785644/98367655-f7c15280-2070-11eb-8fea-eafc764da1ae.png)
He only generated these files for me，I don't know what i should do
