### ISSUE TITLE
Dimensionality change

### ISSUE THREAD

**Issue by jkamalu** [Kyubyong/tacotron#14]
In the tacotron paper, the expected dimensionality of the tensor during most of the encoder cbhg module is expected to be batch size x time steps x num features where num features = 128. Why do you shift to 256 before the bidirectional GRU layer? It seems like this would result in a real loss of information during encoding. Is this somehow what is described in the paper and I am just missing it? Thanks

**Comment by Spotlight0xff** [comment]
Yes, I noticed that as well.
I believe I fixed that with my [PR](https://github.com/Kyubyong/tacotron/pull/11).
Look again at the code, seems fine to me now.
