### ISSUE TITLE
Character Embedding

### ISSUE THREAD

**Issue by tozangezan** [Kyubyong/tacotron#18]
In this implementation, is input sentence raw text rather than 256 embedded values? Does the idea (using raw text) derive from the smaller size of character set?
I thought character embedding in the original article meant [this](http://colinmorris.github.io/blog/1b-words-char-embeddings) kind of method.

**Comment by candlewill** [comment]
@tozangezan In my opinion, the input of **encoder** is raw sentence index, but in the function of **encoder**, these sentence index are converted to embeddings of shape **hp.embed_size**. More detail can be found in the source code:
```
with tf.variable_scope('encoder'):
	# Load vocabulary 
	char2idx, idx2char = load_vocab()

	# Character Embedding
	inputs = embed(x, len(char2idx), hp.embed_size)  # x dim: (N, T);  output dim: (N, T, 256); 256 is the char dim
```

**Comment by Kyubyong** [comment]
candlewill's answer is correct.
