### ISSUE TITLE
Dropbox [SOLVED]

### ISSUE THREAD

**Issue by saeedbinhamad** [Kyubyong/tacotron#24]
Can you share your dropbox already cut training files? Thanks

**Comment by onyedikilo** [comment]
This CSTR VCTK Corpus includes speech data uttered by 109 native speakers of English with various accents. Each speaker reads out about 400 sentences, most of which were selected from a newspaper plus the Rainbow Passage and an elicitation paragraph intended to identify the speaker's accent. The newspaper texts were taken from The Herald (Glasgow), with permission from Herald & Times Group. Each speaker reads a different set of the newspaper sentences, where each set was selected using a greedy algorithm designed to maximise the contextual and phonetic coverage. The Rainbow Passage and elicitation paragraph are the same for all speakers. The Rainbow Passage can be found in the International Dialects of English Archive: (http://web.ku.edu/~idea/readings/rainbow.htm). The elicitation paragraph is identical to the one used for the speech accent archive (http://accent.gmu.edu). The details of the the speech accent archive can be found at http://www.ualberta.ca/~aacl2009/PDFs/WeinbergerKunath2009AACL.pdf

All speech data was recorded using an identical recording setup: an omni-directional head-mounted microphone (DPA 4035), 96kHz sampling frequency at 24 bits and in a hemi-anechoic chamber of the University of Edinburgh. All recordings were converted into 16 bits, were downsampled to 48 kHz based on STPK, and were manually end-pointed. This corpus was recorded for the purpose of building HMM-based text-to-speech synthesis systems, especially for speaker-adaptive HMM-based speech synthesis using average voice models trained on multiple speakers and speaker adaptation technologies.

COPYING 
This corpus is licensed under Open Data Commons Attribution License (ODC-By) v1.0. 

http://homepages.inf.ed.ac.uk/jyamagis/page3/page58/page58.html

**Comment by Kyubyong** [comment]
I'm sharing all of my data. Please see README.md.

**Comment by saeedbinhamad** [comment]
how long is the training should take on non GPU laptops? its been 6 hours now on macbook pro 2016 edition and it is still training.. any idea whether i should interrupt the training or not?

**Comment by Kyubyong** [comment]
I highly doubt if you can train this model without a gpu. In my opinion, it will take dozens of days with multiple gpus.
