### ISSUE TITLE
A question for the concat process when forming the input to the decode RNNs 

### ISSUE THREAD

**Issue by huangjx07** [Kyubyong/tacotron#28]
Hi. Thanks for your codes to help me study a lot, while I have a question after reading you codes. In chapter 3.3, the second sentence, "We concatenate the context vector and the attention RNN cell output to form the input to the decoder RNNS." In your codes, I can not find the concat process.  Do you forget to do or you think it is not necessary?

**Comment by Spotlight0xff** [comment]
He uses concat to form the  input to the decoder, implicitly.

In `attention_decoder` (https://github.com/Kyubyong/tacotron/blob/master/modules.py#L215) he uses the contrib module ´seq2seq´ which allows abstraction over the attention mechanism in the ´seq2seq´ module (you can look at the code [here](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/seq2seq/python/ops/dynamic_attention_wrapper.py)).

The `DynamicAttentionWrapper` uses by default concatenation (defined [here](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/seq2seq/python/ops/dynamic_attention_wrapper.py#L456)).

**Comment by huangjx07** [comment]
@Spotlight0xff Thanks for your answer.

**Comment by basuam** [comment]
If this is not an issue anymore, please close it.
