### ISSUE TITLE
Is it only for CPU training?

### ISSUE THREAD

**Issue by basuam** [Kyubyong/tacotron#5]
I've been trying to train using the GPU but so far I haven't been success.

I changed the _"with tf.device('cpu:0'):"_ command into **with tf.device('gpu:0'):** in the function _def get_batch(is_training=True):_ defined in the _train.py_ file, but I got an error: 

> InvalidArgumentError (see above for traceback): Cannot assign a device to node 'batch': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
> Colocation Debug Info:
> Colocation group had the following types and devices:
> QueueEnqueueV2: CPU
> QueueSizeV2: CPU
> QueueCloseV2: CPU
> QueueDequeueManyV2: CPU
> PaddingFIFOQueueV2: CPU
>          [[Node: batch = QueueDequeueManyV2[component_types=[DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/device:GPU:0"](batch/padding_fifo_queue, batch/n)]]

I also modified in the main() function right after _sv.managed_session_
>         with sv.managed_session() as sess:
>             with tf.device("/gpu:0"):

But still it does not use the GPUs

What must be done to enable GPUs trainig?

**Comment by marcossilva** [comment]
You need to install the tensorflow-gpu to do so

Check it out on [Tensor Flow Installation](https://www.tensorflow.org/install/install_linux)

**Comment by basuam** [comment]
@marcossilva 
Thank you for your prompt answer. I already have install Tensorflow for GPU. I've been training with GPU months ago but for the code released, so far, I haven't figured out why it does not use my GPU.

When typing **nvidia-smi** I can see the projects that are running on the GPU and this code does not run on the GPU. Do you see that your code is running in the GPU when typing **nvidia-smia**?

**Comment by marcossilva** [comment]
@basuam I haven't checked with the **nvidia-smi** because when the training or the evaluation starts it shows that it allocated my GPU0 (my only GPU in fact) to the training. I double checked here just to be sure and it shows python3 in the **nvidia-smi** processes. Are you using a **virtualenv** to make sure the requirements are correct and thath the tensorflow package isn't installed, just the tensorflow-gpu?

**Comment by basuam** [comment]
@marcossilva 
I'm running with Python 2.7.5 and I do not see that message that my GPU has been allocated.
Maybe that's the problem. Let me try with Python 3.
Thank you for your help.

**Comment by basuam** [comment]
Closing this issue because now it is clear that Python3 is need for the GPU capability.
