### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by kyoguan** [Kyubyong/tacotron#59]
running the train.py after 1d 23h, it use lots of ram, and the training speed from 2.23b/s down to 18.5b/s

top - 08:47:16 up 2 days, 18:20,  2 users,  load average: 10.53, 8.43, 7.01
Tasks: 248 total,   1 running, 247 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  0.4 sy,  0.0 ni, 77.5 id, 20.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16363244 total,   329000 free, 15569480 used,   464764 buff/cache
KiB Swap: 16707580 total, 10609236 free,  6098344 used.   275080 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                      
21894 kyo       20   0 47.847g 0.014t 171628 S  15.2 93.2   1742:11 python

**Comment by kyoguan** [comment]
<img width="1041" alt="13500" src="https://user-images.githubusercontent.com/29282500/27667370-f4413ebc-5cac-11e7-9d16-d2b1224eb187.png">

after 135000 gs training, the voices became more clear.

**Comment by jpdz** [comment]
Hi, can you share your samples generated? I also trained the model, however the loss is always above 1.0
Thanks a lot!
