### ISSUE TITLE
Help load_vocab function!

### ISSUE THREAD

**Issue by keicoon** [Kyubyong/tacotron#64]
`prepro.py`
```
def load_vocab():
    vocab = "EG abcdefghijklmnopqrstuvwxyz'" # E: Empty. ignore G
    char2idx = {char:idx for idx, char in enumerate(vocab)}
    idx2char = {idx:char for idx, char in enumerate(vocab)}
    return char2idx, idx2char
```
This `load_vacab` surpport only char [a-z']. I saw tacotron possible interpreting 256 characters. Why using char2idx instead of ascii function(ord)?

**Comment by AzamRabiee** [comment]
It's not a big deal. depending on the type of dataset you can make your own vocab index list. specially for TTS, capital or small characters are same. Special characters may be useful for future extend to include emotion or characteristics of the person.

**Comment by keicoon** [comment]
Thanks for answer!
