### ISSUE TITLE
Not training

### ISSUE THREAD

**Issue by ahmed-tbox** [Kyubyong/tacotron#67]
Hi guys,

for some reason this bit of code is not running on our dataset
`

for step in tqdm(range(g.num_batch), total=g.num_batch, ncols=70, leave=False, unit='b'):
    sess.run(g.train_op)

`
we got about 170 audio files about 30 seconds each. The script finishes running the main program with the print("Done"), but I don't think there's any training happening. Any thoughts?

**Comment by zuoxiang95** [comment]
@ahmed-tbox you can add this code in the  train.py L126
train_loss = sess.run(g.mean_loss)
print('After %d epoches, the mean loss is %f' % (epoch, train_loss))

and you can see the loss every epoch. You can also use tensorboard to see it.

**Comment by ahmed-tbox** [comment]
@zuoxiang95 I got thrown this error.
`  File "train.py", line 131, in <module>
    main()
  File "train.py", line 128, in main
    train_loss = sess.run(g.mean_loss)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 925, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.`

**Comment by zuoxiang95** [comment]
@ahmed-tbox I guess you misplaced it.
![1499912029 1](https://user-images.githubusercontent.com/20696420/28147573-2e02e238-67b4-11e7-9241-c4afb265c29e.jpg)

**Comment by ahmed-tbox** [comment]
Excellent! Got it working thank you so much @zuoxiang95 it looks like it wasn't training because we had to decrease the batch_size and got it to work.
