### ISSUE TITLE
How to control the length of generated wav???

### ISSUE THREAD

**Issue by zuoxiang95** [Kyubyong/tacotron#71]
hey guys, i want to ask how to control  the length of generated wav. i find the generated wav is about 4s. If my text is too long,  it can not be finished in 4s. what should i do?

**Comment by keicoon** [comment]
I found this script in `eval.py` 44 line.
```
timesteps = 100  # Adjust this number as you want
```
Modify this script to want you increasing timesteps value.

**Comment by zuoxiang95** [comment]
@keicoon You are right. Thanks!
