### ISSUE TITLE
Cell output not passed to the decoder RNN

### ISSUE THREAD

**Issue by candlewill** [Kyubyong/tacotron#82]
As mentioned in issue https://github.com/Kyubyong/tacotron/issues/28, I think the issue is still a problem.

From the [code](https://github.com/Kyubyong/tacotron/blob/master/modules.py#L249), we can know that the variable `cell_with_attention` only contains the attention information,  but not the output of a `cell`. 

```python
cell_with_attention = tf.contrib.seq2seq.AttentionWrapper(decoder_cell, attention_mechanism, num_units)
outputs, _ = tf.nn.dynamic_rnn(cell_with_attention, inputs, 
                                      dtype=tf.float32) #( N, T', 16)
```

The reason is that `tf.contrib.seq2seq.AttentionWrapper` has a parameter `output_attention` with default value `True`, which means the output at each time step is the attention value. We can see from the [TF doc](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/AttentionWrapper):
```python
__init__(
    cell,
    attention_mechanism,
    attention_layer_size=None,
    alignment_history=False,
    cell_input_fn=None,
    output_attention=True,
    initial_cell_state=None,
    name=None
)
```
```
output_attention: Python bool. If True (default), the output at each time step is the attention value. This is the behavior of Luong-style attention mechanisms.
```

To fix this, we should set `output_attention=False`, and use a wrapper to concate the attention and the cell output.

Is my understanding right?

**Comment by Kyubyong** [comment]
Why do you think we have to concatenate the **attention** and the cell output?
The paper says that they concatenate **the context (vector)** and the attentional RNN cell output to form the input to the decoder RNNS.
I thought it was implicitly processed here: https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L745, regardless of the arguement of `output_attention`.
Corret me if I'm wrong.

**Comment by candlewill** [comment]
I misunderstood it. Thanks.
